services:
  api:
    build:
      dockerfile: docker/api.Dockerfile
      context: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    depends_on:
      - postgres
    volumes:
      - .:/urs/src/app
      - node-modules:/urs/src/app/node_modules
    env_file:
      - .env
    networks:
      - db

  postgres:
    build:
      dockerfile: docker/pg.Dockerfile
      context: .
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - db

networks:
  db:
    driver: bridge
volumes:
  postgres:
  node-modules: