openapi: 3.0.0
paths:
  /user:
    post:
      operationId: UsersController_create
      summary: Create user.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: User created.
        '400':
          description: Invalid request.
      tags:
        - User
    get:
      operationId: UsersController_findAll
      summary: Get all users.
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      tags:
        - User
  /user/{id}:
    get:
      operationId: UsersController_findOne
      summary: Get user by id.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request.
        '404':
          description: User not found.
      tags:
        - User
    put:
      operationId: UsersController_update
      summary: Change password.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePasswordDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request.
        '403':
          description: Wrong password.
        '404':
          description: User not found.
      tags:
        - User
    delete:
      operationId: UsersController_remove
      summary: Delete user.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '204':
          description: User deleted.
        '400':
          description: Invalid request.
        '404':
          description: User not found.
      tags:
        - User
  /artist:
    post:
      operationId: ArtistController_create
      summary: Create artist.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateArtistDto'
      responses:
        '201':
          description: Artist created.
        '400':
          description: Invalid request.
      tags:
        - Artist
    get:
      operationId: ArtistController_findAll
      summary: Get all artists.
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Artist'
      tags:
        - Artist
  /artist/{id}:
    get:
      operationId: ArtistController_findOne
      summary: Get artist by id.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artist'
        '400':
          description: Invalid request.
        '404':
          description: Artist not found.
      tags:
        - Artist
    put:
      operationId: ArtistController_update
      summary: Update artist.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateArtistDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artist'
        '400':
          description: Invalid request.
        '404':
          description: Artist not found.
      tags:
        - Artist
    delete:
      operationId: ArtistController_remove
      summary: Delete artist.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '204':
          description: Artist deleted.
        '400':
          description: Invalid request.
        '404':
          description: Artist not found.
      tags:
        - Artist
  /track:
    post:
      operationId: TrackController_create
      summary: Create track.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTrackDto'
      responses:
        '201':
          description: Track created.
        '400':
          description: Invalid request.
      tags:
        - Track
    get:
      operationId: TrackController_findAll
      summary: Get all tracks.
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Track'
      tags:
        - Track
  /track/{id}:
    get:
      operationId: TrackController_findOne
      summary: Get track by id.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Track'
        '400':
          description: Invalid request.
        '404':
          description: Track not found.
      tags:
        - Track
    put:
      operationId: TrackController_update
      summary: Update track.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTrackDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Track'
        '400':
          description: Invalid request.
        '404':
          description: Track not found.
      tags:
        - Track
    delete:
      operationId: TrackController_remove
      summary: Delete track.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '204':
          description: Track deleted.
        '400':
          description: Invalid request.
        '404':
          description: Track not found.
      tags:
        - Track
  /favs:
    get:
      operationId: FavouritesController_getAll
      summary: Get all favorite tracks, albums and artists.
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FavoritesRepsonse'
      tags:
        - Favs
  /favs/track/{id}:
    post:
      operationId: FavouritesController_addTrack
      summary: Add track to favorites.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '201':
          description: Track added to favorites.
        '400':
          description: Invalid request.
        '422':
          description: Track not found.
      tags:
        - Favs
    delete:
      operationId: FavouritesController_removeTrack
      summary: Remove track from favorites.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '204':
          description: Track removed from favorites.
        '400':
          description: Invalid request.
        '404':
          description: Track not found in favorites.
      tags:
        - Favs
  /favs/album/{id}:
    post:
      operationId: FavouritesController_addAlbum
      summary: Add album to favorites.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '201':
          description: Album added to favorites.
        '400':
          description: Invalid request.
        '422':
          description: Album not found.
      tags:
        - Favs
    delete:
      operationId: FavouritesController_removeAlbum
      summary: Remove album from favorites.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '204':
          description: Album removed from favorites.
        '400':
          description: Invalid request.
        '404':
          description: Album not found in favorites.
      tags:
        - Favs
  /favs/artist/{id}:
    post:
      operationId: FavouritesController_addArtist
      summary: Add artist to favorites.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '201':
          description: Artist added to favorites.
        '400':
          description: Invalid request.
        '422':
          description: Artist not found.
      tags:
        - Favs
    delete:
      operationId: FavouritesController_removeArtist
      summary: Remove artist from favorites.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '204':
          description: Artist removed from favorites.
        '400':
          description: Invalid request.
        '404':
          description: Artist not found in favorites.
      tags:
        - Favs
  /album:
    post:
      operationId: AlbumController_create
      summary: Create album.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAlbumDto'
      responses:
        '201':
          description: Album created.
        '400':
          description: Invalid request.
      tags:
        - Album
    get:
      operationId: AlbumController_findAll
      summary: Get all albums.
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Album'
      tags:
        - Album
  /album/{id}:
    get:
      operationId: AlbumController_findOne
      summary: Get album by id.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
        '400':
          description: Invalid request.
        '404':
          description: Album not found.
      tags:
        - Album
    put:
      operationId: AlbumController_update
      summary: Update album.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAlbumDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
        '400':
          description: Invalid request.
        '404':
          description: Album not found.
      tags:
        - Album
    delete:
      operationId: AlbumController_remove
      summary: Delete album.
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '204':
          description: Album deleted.
        '400':
          description: Invalid request.
        '404':
          description: Album not found.
      tags:
        - Album
info:
  title: Home Library Service
  description: Home Library Service
  version: 0.0.1
  contact: {}
tags: []
servers: []
components:
  schemas:
    CreateUserDto:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
      required:
        - login
        - password
    User:
      type: object
      properties:
        id:
          type: string
        login:
          type: string
        password:
          type: string
        version:
          type: number
        createdAt:
          type: number
        updatedAt:
          type: number
      required:
        - id
        - login
        - password
        - version
        - createdAt
        - updatedAt
    UpdatePasswordDto:
      type: object
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
      required:
        - oldPassword
        - newPassword
    CreateArtistDto:
      type: object
      properties:
        name:
          type: string
        grammy:
          type: boolean
      required:
        - name
        - grammy
    Artist:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        grammy:
          type: boolean
      required:
        - id
        - name
        - grammy
    UpdateArtistDto:
      type: object
      properties:
        name:
          type: string
        grammy:
          type: boolean
    CreateTrackDto:
      type: object
      properties:
        name:
          type: string
        artistId:
          type: string
        albumId:
          type: string
        duration:
          type: number
      required:
        - name
        - duration
    Track:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        artistId:
          type: string
          nullable: true
        albumId:
          type: string
          nullable: true
        duration:
          type: number
      required:
        - id
        - name
        - artistId
    UpdateTrackDto:
      type: object
      properties:
        name:
          type: string
        artistId:
          type: string
        albumId:
          type: string
        duration:
          type: number
    Album:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        year:
          type: number
        artistId:
          type: string
          nullable: true
      required:
        - id
        - name
        - year
    FavoritesRepsonse:
      type: object
      properties:
        artists:
          type: array
          items:
            $ref: '#/components/schemas/Artist'
        albums:
          type: array
          items:
            $ref: '#/components/schemas/Album'
        tracks:
          type: array
          items:
            $ref: '#/components/schemas/Track'
      required:
        - artists
        - albums
        - tracks
    CreateAlbumDto:
      type: object
      properties:
        name:
          type: string
        year:
          type: number
        artistId:
          type: string
          nullable: true
      required:
        - name
        - year
    UpdateAlbumDto:
      type: object
      properties:
        name:
          type: string
        year:
          type: number
        artistId:
          type: string
          nullable: true
